version: "3"
services:
  web:
    image: maxhoffman/muttmatch:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    deploy: 
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports: 
      - "80:80"
    depends_on:
      - db
    command: ["./bin/wait-for-it.sh", "db:5432", "--", "node", "server/index.js"]
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/muttmatch
    networks:
      - webnet
  db:
    image: postgres:9.4
    ports:
      - "8998:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: muttmatch
    volumes: 
      - data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "5000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks: 
  webnet:
volumes:
  data:
    external: true
